# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/slurm-lightning',
                'doc_host': 'https://TahaK.github.io',
                'git_url': 'https://github.com/TahaK/slurm-lightning',
                'lib_path': 'slurm_lightning'},
  'syms': {'slurm_lightning.core': {'slurm_lightning.core.foo': ('core.html#foo', 'slurm_lightning/core.py')}}}
