# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_train.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/02_train.ipynb 4
import os
from argparse import ArgumentParser
from lightning.pytorch.loggers import WandbLogger
